### ISSUE TITLE
[RELEASE] Add the screenshots of the client to the README.md 

### ISSUE THREAD

**Issue by Ali00035v2** [HazeClient/Haze#3]
Like there should be screenshots of the ClickGUI, HUD, ESP, and more Render/Visual related stuff on the README.md

So the users can see what the client looks like before downloading.

**Comment by Cypphi** [comment]
yes, that's the plan, just not in the README.md. Probably making a wiki

**Comment by Ali00035v2** [comment]
> yes, that's the plan, just not in the README.md. Probably making a wiki

Really good idea

**Comment by Cypphi** [comment]
Will keep this in mind

**Comment by Ali00035v2** [comment]
> Will keep this in mind

**Pinning exists**

**Comment by Cypphi** [comment]
ok? its not important for now as the client isn't anywhere near done

**Comment by Ali00035v2** [comment]
> ok? its not important for now as the client isn't anywhere near done

Okay.

**Comment by Cypphi** [comment]
XD
